sudo: required
dist: trusty
language: java
jdk: oraclejdk8
addons:
  ssh_known_hosts:
    - 47.93.42.145:22008
  sonarcloud:
    organization: stabila2021
    token:
      secure: "a556ae0cae90d05aeb8d93c86ae91ff461e88489"
cache:
  directories:
  - '$HOME/.sonar/cache'
matrix:
  include:
    - name: build
      script:
        - sh stabila.sh
        - "./gradlew build"
        - "./gradlew jacocoTestReport"


    - name: stest
      script:
        - sh stabila.sh
        - bash deploy.sh


after_success:
  - "bash <(curl -s https://codecov.io/bash)"

skip_build:
  - README.md：
  - LICENSE




